FROM alpine:3.20
RUN apk add --no-cache bash iproute2 iptables iputils-ping ca-certificates
# WORKDIR /chaos
# COPY chaos.sh .
# ENTRYPOINT ["bash","/chaos/chaos.sh"]

ENTRYPOINT ["sleep", "infinity"]
